version: 2

jobs:
  build:
    macos:
      xcode: 9.2.0
    steps:
      - checkout
      - restore_cache:
          key: v2-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install --path .bundle --jobs 3 --retry 3
      - save_cache:
          key: v2-gems-{{ checksum "Gemfile.lock" }}
          paths: .bundle

      - run: xcodebuild -destination 'platform=iOS Simulator,name=iPhone 6s' -sdk iphonesimulator -workspace WordPress.xcworkspace -scheme WordPress -configuration Debug build test | bundle exec xcpretty -f `bundle exec xcpretty-travis-formatter`
