version: 2

jobs:
  build:
    macos:
      xcode: 9.2.0
    steps:
      - checkout
      - restore_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
      - restore_cache:
          key: v1-pods-{{ checksum "Podfile.lock" }}

      - run: rake dependencies
      - run: bundle exec pod install

      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle
      - save_cache:
          key: v1-pods-{{ checksum "Podfile.lock" }}
          paths: Pods

      - run: rake test
