version: 2

jobs:
  build:
    macos:
      xcode: 9.2.0
    steps:
      - checkout
      - run: curl -sS https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash
      - restore_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
      - run: rake dependencies
      - save_cache:
          key: v1-gems-{{ checksum "Gemfile.lock" }}
          paths: vendor/bundle
      - restore_cache:
          key: v1-pods-{{ checksum "Podfile.lock" }}
      - run: bundle exec pod install
      - save_cache:
          key: v1-pods-{{ checksum "Podfile.lock" }}
          paths: Pods
      - run: rake build
